version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running pre-build tasks...
  build:
    commands:
      - echo Running build tasks...
      - sam build --template template.yaml
  post_build:
    commands:
      - echo Running post-build tasks...

artifacts:
  files:
    - template.yaml
    - .aws-sam/build/**/*

