AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Middleware to connect with Klavi.

Parameters:
  SESIdentityName:
    Type: String
    Default: "juntos@pontte.com.br"
    Description: An email

  Project:
    Description: nome do projeto
    Type: String
    Default: Klavi

  Environment:
    Description: Environment de execucao do servico
    Type: String
    AllowedValues:
      - dev
      - test
      - staging
      - prod
      - refactoring
    Default: dev

  APIDomainName:
    Description: Nome do dominio
    Type: String

  CognitoUserPoolArn:
    Description: ARN do User Pool do Cognito
    Type: String

  StageName:
    Description: nome do estagio na URL quando em producao
    Type: String

Globals:
  Function:
    Runtime: python3.8
    MemorySize: 1024
    ReservedConcurrentExecutions: 12
    Timeout: 120
    Layers:
      - arn:aws:lambda:us-east-1:848638426587:layer:LibrariesLayer:2621
      - arn:aws:lambda:us-east-1:848638426587:layer:CommonLayer:2023
    Environment:
      Variables:
        ENV: !Ref Environment
        EVENT_TABLE: !Sub "Klavi-EventsTable.${Environment}"
        REPORT_TABLE: !Sub "klavi-ReportTable.${Environment}"
        LOGGING_LEVEL: DEBUG
        SMTP_SERVER: 'email-smtp.us-east-1.amazonaws.com'
        SENDING_IDENTITY_ARN: "arn:aws:ses:us-east-1:848638426587:identity/juntos@pontte.com.br"
        CONFIG_SET: "klavi"
        SMTP_PORT: 508
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Authorization,Content-Type,If-Match'"
      AllowOrigin: "'*'"

Conditions:
  Prod: !Equals [ !Ref Environment, prod ]

Resources:
  KlaviBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "klavi-${Environment}"

  APIDomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      DomainName: !Sub "OpenFinanceApi{Environment}.pontte.com.br"
      CertificateArn: "arn:aws:acm:us-east-1:848638426587:certificate/639f5ab2-c77a-4f62-8250-c85716a6753f"

  # Acessos para log
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  KlaviApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "OpenFinance-${Environment}"
      StageName: !Ref Environment

  KlaviApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: "open-finance"
      DomainName: !Ref APIDomainName
      RestApiId: !Ref KlaviApi
      Stage: !Ref KlaviApi.Stage

  MidKlaviFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "KlaviWebhookFn-${Environment}"
      Description: Middleware to connect with Klavi
      CodeUri: src/create/
      Handler: app.handler
      Tracing: Active
      Events:
        api1:
          Type: Api
          Properties:
            RestApiId: !Ref KlaviApi
            Path: /create
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventReportTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ReportTable
        - S3CrudPolicy:
            BucketName: !Ref KlaviBucket
        - SESCrudPolicy:
            IdentityName: !Ref SESIdentityName

  EventReportTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "ReportURLs.${Environment}"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [ Prod, true, false ]
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: enquiry_cpf
          AttributeType: S
        - AttributeName: report_type
          AttributeType: S
      KeySchema:
        - AttributeName: enquiry_cpf
          KeyType: HASH
        - AttributeName: report_type
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: Project
          Value: open-finance
        - Key: Environment
          Value: !Ref Environment

  ReportTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "UserInformation"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: enquiry_cpf
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: Project
          Value: open-finance
      GlobalSecondaryIndexes:
        - IndexName: CPFIndex
          KeySchema:
            - AttributeName: enquiry_cpf
              KeyType: HASH
          Projection:
            ProjectionType: ALL



