AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Middleware to connect with Klavi.

Parameters:
  ProjectName:
    Description: Project Name
    Type: String
    Default: Klavi

  Environment:
    Description: Execution environment for the service
    Type: String
    AllowedValues:
      - dev
      - test
      - staging
      - prod
      - refactoring
    Default: dev

Globals:
  Function:
    Runtime: python3.8
    MemorySize: 1024
    Timeout: 120
    Environment:
      Variables:
        ENV: !Ref Environment
        LOGGING_LEVEL: DEBUG
    Tags:
      Project: !Ref ProjectName
      Environment: !Ref Environment
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Authorization,Content-Type,If-Match'"
      AllowOrigin: "'*'"
    Variables:
      Environment: !Ref Environment

Conditions:
  Prod: !Equals [ !Ref Environment, prod ]

Resources:
  # Bucker para guardar os arquivos exportados pelo webhook
  KlaviBucker:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "Klavi-${Environment}"

  # Domínio para o API Gateway
  APIDomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      DomainName: !Sub "api-klavi${Environment}.pontte.com.br"
      CertificateArn: "arn:aws:acm:us-east-1:848638426587:certificate/639f5ab2-c77a-4f62-8250-c85716a6753f"

  # Acessos para log
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  KlaviApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "KlaviApi-${Environment}"
      StageName: !Ref Environment

  KlaviApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: "KlaviApiMapping"
      DomainName: !Ref APIDomainName
      RestApiId: !Ref KlaviApi
      Stage: !Ref KlaviApi.Stage


  MidKlaviFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "KlaviWebhookFn-${Environment}"
      CodeUri: src/klavi_webhook/
      Handler: app.lambda_handler
      Events:
        CreateApi:
          Type: Api
          Properties:
            Path: /create
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: !Ref EventLoggerTable
          ENV: !Ref Environment
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventLoggerTable


  ActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "date"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "KlaviApi-Activities-${Environment}"

  EventLoggerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: !Sub "KlaviApi-EventLogger-${Environment}"

  CategoryCheckingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "report_id"
          AttributeType: "S"
      KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "report_id"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: !Sub "KlaviApi-CategoryChecking-${Environment}"

  TransactionDetailTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "category_d"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "category_d"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: !Sub "KlaviApi-TransactionDetail-${Environment}"
