AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Middleware to connect with Klavi.

Parameters:
  ProjectName:
    Description: Project Name
    Type: String
    Default: Klavi

  Environment:
    Description: Execution environment for the service
    Type: String
    AllowedValues:
      - dev
      - test
      - staging
      - prod
      - refactoring
    Default: dev

  PipefyDatabaseID:
    Description: ID of Database used to save klavi report information inside of Pipefy
    Type: String
    Default: "303051866"
  PipefyPipeID:
    Description: ID of Database used to save klavi report information inside of Pipefy
    Type: String
    Default: "303051849"

Globals:
  Function:
    Runtime: python3.8
    MemorySize: 1024
    Timeout: 120
    Environment:
      Variables:
        ENV: !Ref Environment
        LOGGING_LEVEL: DEBUG
    Tags:
      Project: !Ref ProjectName
      Environment: !Ref Environment
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Authorization,Content-Type,If-Match'"
      AllowOrigin: "'*'"
    Variables:
      Environment: !Ref Environment

Conditions:
  Prod: !Equals [ !Ref Environment, prod ]

Resources:
  # Bucker para guardar os arquivos exportados pelo webhook
  KlaviBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "klavi-${Environment}"

  # Domínio para o API Gateway
  APIDomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      DomainName: !Sub "api-klaviwebhook${Environment}.pontte.com.br"
      CertificateArn: "arn:aws:acm:us-east-1:848638426587:certificate/639f5ab2-c77a-4f62-8250-c85716a6753f"

  # Acessos para log
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  KlaviApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "KlaviApi-${Environment}"
      StageName: !Ref Environment

  KlaviApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: "klavi-webhook"
      DomainName: !Ref APIDomainName
      RestApiId: !Ref KlaviApi
      Stage: !Ref KlaviApi.Stage


  MidKlaviFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "KlaviWebhookFn-${Environment}"
      Tracing: Active
      CodeUri: src/klavi_webhook/
      Handler: app.lambda_handler
      Events:
        api1:
          Type: Api
          Properties:
            RestApiId: !Ref KlaviApi
            Path: /create
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: !Ref EventLoggerTable
          KLAVI_REPORTS_BUCKET_NAME: !Sub "silvio-jr-klavi-${Environment}"
          PIPEFY_KLAVI_DATABASE_ID: !Ref PipefyDatabaseID
          PIPEFY_KLAVI_PIPE_ID: !Ref PipefyPipeID
          ENV: !Ref Environment
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref KlaviBucket
        - DynamoDBWritePolicy:
            TableName: !Ref CategoryCreditCardTable
        - DynamoDBWritePolicy:
            TableName: !Ref OpenStatementTable
        - DynamoDBWritePolicy:
            TableName: !Ref ClosedStatementTable
        - DynamoDBWritePolicy:
            TableName: !Ref CategoryCheckingTable
        - DynamoDBWritePolicy:
            TableName: !Ref FinancialInsightTable
        - DynamoDBWritePolicy:
            TableName: !Ref CashflowAnalysisTable
        - DynamoDBWritePolicy:
            TableName: !Ref CreditAnalysisTable
        - DynamoDBWritePolicy:
            TableName: !Ref CreditcardSpendingTable
        - DynamoDBWritePolicy:
            TableName: !Ref FinancialProfileTable
        - DynamoDBWritePolicy:
            TableName: !Ref LiabilitiesTable
        - DynamoDBWritePolicy:
            TableName: !Ref LiabilityStreamTable
        - DynamoDBWritePolicy:
            TableName: !Ref LiabilityTransactionTable
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionDetailTable
        - DynamoDBWritePolicy:
            TableName: !Ref EventLoggerTable
        - DynamoDBWritePolicy:
            TableName: !Ref KlaviReportTable
        - DynamoDBWritePolicy:
            TableName: !Ref IdentityTable
        - DynamoDBWritePolicy:
            TableName: !Ref ScoreK1Table
        - DynamoDBWritePolicy:
            TableName: !Ref RiskLabelTable
        - DynamoDBWritePolicy:
            TableName: !Ref IncomeTable
        - DynamoDBWritePolicy:
            TableName: !Ref IncomeStreamTable
        - DynamoDBWritePolicy:
            TableName: !Ref IncomeTransactionTable
        - DynamoDBWritePolicy:
            TableName: !Ref BalanceTable
        - DynamoDBWritePolicy:
            TableName: !Ref LabelDetailTable

  CategoryCreditCardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-CategoryCreditCard-${Environment}"

  OpenStatementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-OpenStatement-${Environment}"

  ClosedStatementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-ClosedStatement-${Environment}"

  CategoryCheckingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-CategoryChecking-${Environment}"

  FinancialInsightTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-FinancialInsight-${Environment}"

  CashflowAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-CashflowAnalysis-${Environment}"

  CreditAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-CreditAnalysis-${Environment}"

  CreditcardSpendingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-CreditcardSpending-${Environment}"

  FinancialProfileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-FinancialProfile-${Environment}"

  LiabilitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-Liabilities-${Environment}"

  LiabilityStreamTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-LiabilityStream-${Environment}"

  LiabilityTransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-LiabilityTransaction-${Environment}"

  TransactionDetailTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-TransactionDetail-${Environment}"

  EventLoggerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-EventLogger-${Environment}"

  KlaviReportTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-KlaviReport-${Environment}"

  IdentityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-Identity-${Environment}"

  ScoreK1Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-ScoreK1-${Environment}"

  RiskLabelTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-RiskLabel-${Environment}"

  IncomeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-Income-${Environment}"

  IncomeStreamTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-IncomeStream-${Environment}"

  IncomeTransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-IncomeTransaction-${Environment}"

  BalanceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-Balance-${Environment}"

  LabelDetailTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "Klavi-LabelDetail-${Environment}"

