AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Middleware to connect with Klavi.

Parameters:
  ProjectName:
    Description: Project Name
    Type: String
    Default: Klavi

  Environment:
    Description: Execution environment for the service
    Type: String
    AllowedValues:
      - dev
      - test
      - staging
      - prod
      - refactoring

  Table:
    Type: String
    Default: Activities
  Region:
    Type: String
    Default: us-east-1
  AWSEnv:
    Type: String
    Default: AWS

Globals:
  Function:
    Runtime: python3.9
    MemorySize: 1024
    Timeout: 120
    Environment:
      Variables:
        ENV: !Ref Environment
        LOGGING_LEVEL: DEBUG
        TABLE: !Ref Table
        REGION: !Ref Region
        AWSENV: !Ref AWSEnv
    Tags:
      Project: !Ref ProjectName
      Environment: !Ref Environment
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Authorization,Content-Type,If-Match'"
      AllowOrigin: "'*'"
    Variables:
      Environment: !Ref Environment

Resources:
  KlaviApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Name: KlaviApi
      Variables:
        ENV: !Ref Environment

  KlaviApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !GetAtt KlaviApi.DomainName
      RestApiId: !Ref KlaviApi
      Stage: !Ref KlaviApi.StageName
      BasePath: api

#  EventLogerTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      TableName: Klavi_EventLoger
#      AttributeDefinitions:
#        - AttributeName: id
#          AttributeType: S
#      KeySchema:
#        - AttributeName: id
#          KeyType: HASH
#      ProvisionedThroughput:
#        ReadCapacityUnits: 1
#        WriteCapacityUnits: 1

#  CreateFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      FunctionName: create
#      CodeUri: src/klavi_webhook/
#      Handler: app.lambda_handler
#      Events:
#        CreateApi:
#          Type: Api
#          Properties:
#            Path: /create
#            Method: GET
#      Environment:
#        Variables:
#          TABLE_NAME: !Ref EventLogerTable


#  HelloWorldFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      FunctionName: HelloWorldFn
#      CodeUri: src/hello_world/
#      Handler: app.lambda_handler
#      Events:
#        CreateApi:
#          Type: Api
#          Properties:
#            Path: /hello
#            Method: GET
#      Environment:
#        Variables:
#          TABLE_NAME: !Ref EventLogerTable

#  ListActivityFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      FunctionName: ListActivityFunction
#      CodeUri: src/list_activity/
#      Handler: app.lambda_handler
#      Events:
#        CreateApi:
#          Type: Api
#          Properties:
#            Path: /list
#            Method: GET
#      Environment:
#        Variables:
#          TABLE_NAME: !Ref ActivitiesTable
#      Policies:
#        - DynamoDBCrudPolicy:
#            TableName: !Ref ActivitiesTable

  MidKlaviFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MidKlaviFunction
      CodeUri: src/mid_klavi/
      Handler: app.lambda_handler
      Events:
        CreateApi:
          Type: Api
          Properties:
            Path: /create
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: !Ref EventLoggerTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventLoggerTable

  ActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "date"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "Activities"

  EventLoggerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "key"
          AttributeType: "S"
        - AttributeName: "institution_id"
          AttributeType: "S"
        - AttributeName: "enquiry_cpf"
          AttributeType: "S"
        - AttributeName: "report_time"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "key"
          KeyType: "HASH"
        - AttributeName: "instituion_id"
          KeyType: "HASH"
        - AttributeName: "enquiry_cpf"
          KeyType: "HASH"
        - AttributeName: "report_time"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "EventLogger"

  CategoryCheckingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "report_id"
          AttributeType: "S"
        - AttributeName: "bank_name"
          AttributeType: "S"
        - AttributeName: "bacen_name"
          AttributeType: "S"
        - AttributeName: "bacen_id"
          AttributeType: "S"
        - AttributeName: "bank_branch"
          AttributeType: "S"
        - AttributeName: "account"
          AttributeType: "S"
        - AttributeName: "operation_code"
          AttributeType: "S"
        - AttributeName: "cpf_verified"
          AttributeType: "S"
        - AttributeName: "holder_name"
          AttributeType: "S"
        - AttributeName: "balance"
          AttributeType: "S"
      KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "report_id"
            KeyType: "HASH"
          - AttributeName: "bank_name"
            KeyType: "HASH"
          - AttributeName: "bacen_name"
            KeyType: "HASH"
          - AttributeName: "bacen_id"
            KeyType: "HASH"
          - AttributeName: "bank_branch"
            KeyType: "HASH"
          - AttributeName: "account"
            KeyType: "HASH"
          - AttributeName: "operation_code"
            KeyType: "HASH"
          - AttributeName: "cpf_verified"
            KeyType: "HASH"
          - AttributeName: "holder_name"
            KeyType: "HASH"
          - AttributeName: "balance"
            KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "CategoryChecking"

  TransactionDetailTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "category_d"
          AttributeType: "S"
        - AttributeName: "trans_date"
          AttributeType: "S"
        - AttributeName: "trans_amount"
          AttributeType: "S"
        - AttributeName: "trans_description"
          AttributeType: "S"
        - AttributeName: "balance"
          AttributeType: "S"
        - AttributeName: "category"
          AttributeType: "S"
        - AttributeName: "trans_currency"
          AttributeType: "S"
        - AttributeName: "payment_type"
          AttributeType: "S"
        - AttributeName: "charge_identificator"
          AttributeType: "S"
        - AttributeName: "charge_number"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "category_d"
          KeyType: "HASH"
        - AttributeName: "trans_date"
          KeyType: "HASH"
        - AttributeName: "trans_amount"
          KeyType: "HASH"
        - AttributeName: "trans_description"
          KeyType: "HASH"
        - AttributeName: "balance"
          KeyType: "HASH"
        - AttributeName: "category"
          KeyType: "HASH"
        - AttributeName: "trans_currency"
          KeyType: "HASH"
        - AttributeName: "payment_type"
          KeyType: "HASH"
        - AttributeName: "charge_identificator"
          KeyType: "HASH"
        - AttributeName: "charge_number"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "TransactionDetail"
