AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Serverless Application Model (SAM) template for the mid-klavi-test application.

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    Runtime: python3.9
    Handler: app.lambda_handler
    CodeUri: hello_world/
  Api:
    TracingEnabled: true

Resources:
  KlaviReportTestFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - arn:aws:lambda:us-east-1:848638426587:layer:LibrariesLayer:2621
        - arn:aws:lambda:us-east-1:848638426587:layer:CommonLayer:2023
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub 'ApplicationInsights-SAM-${AWS::StackName}'
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  MidKlaviTestApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  KlaviReportTestFn:
    Description: Klavi Report Test Lambda Function ARN
    Value: !GetAtt KlaviReportTestFn.Arn
  KlaviReportTestFnIamRole:
    Description: Implicit IAM Role created for Klavi Report Test function
    Value: !GetAtt KlaviReportTestFnRole.Arn
